name: Merge and Remove Duplicates from Three Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点触发，根据需要调整
  workflow_dispatch:

jobs:
  merge-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download files
        run: |
          echo "Downloading mosdns_adrules.txt..."
          curl -sSL "https://raw.githubusercontent.com/Cats-Team/AdRules/main/mosdns_adrules.txt" -o mosdns_adrules.txt
          echo "Downloading domains.txt (from anti-ad.net)..."
          curl -sSL "https://anti-ad.net/domains.txt" -o domains_raw.txt
          echo "Downloading dns.txt (from GOODBYEADS)..."
          curl -sSL "https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/dns.txt" -o dns_raw.txt

      - name: Process mosdns_adrules.txt (remove "domain:" prefix)
        run: |
          sed 's/^domain://g' mosdns_adrules.txt > mosdns_adrules_processed.txt

      - name: Process domains_raw.txt (remove first three lines)
        run: |
          tail -n +5 domains_raw.txt > domains_processed.txt

      - name: Process dns.txt (remove first seven lines, remove starting "||" and ending "^")
        run: |
          # tail -n +8: 删除前七行（从第8行开始输出）
          tail -n +8 dns_raw.txt > dns_temp.txt
          # 使用 sed 去除每行开头的 "||" 和末尾的 "^"
          sed -E 's/^\|\|//; s/\^$//' dns_temp.txt > dns_processed.txt

      - name: Merge files and remove duplicate entries
        run: |
          # 合并三个处理后的文件，删除空行，然后排序去重生成最终文件 domains.txt
          cat mosdns_adrules_processed.txt domains_processed.txt dns_processed.txt | sed '/^\s*$/d' | sort -u > domains.txt
          echo "Merged domains.txt generated with $(wc -l < domains.txt) unique lines."

      - name: Commit merged file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add domains.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update merged domains file"
            git push
          else
            echo "No changes to commit."
          fi
