name: Merge and Remove Duplicates from Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点触发，根据需要调整
  workflow_dispatch:

jobs:
  merge-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download files
        run: |
          echo "Downloading mosdns_adrules.txt..."
          curl -sSL "https://raw.githubusercontent.com/Cats-Team/AdRules/main/mosdns_adrules.txt" -o mosdns_adrules.txt
          
          echo "Downloading domains.txt (from anti-ad.net)..."
          curl -sSL "https://anti-ad.net/domains.txt" -o domains_raw.txt
          
          echo "Downloading dns.txt (from GOODBYEADS)..."
          curl -sSL "https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/dns.txt" -o dns_raw.txt

          echo "Downloading adblockdomain.txt (from 217heidai/adblockfilters)..."
          curl -sSL "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdomain.txt" -o adblockdomain_raw.txt

      - name: Process mosdns_adrules.txt (remove "domain:" prefix and ignore lines starting with "!")
        run: |
          sed 's/^domain://g' mosdns_adrules.txt | grep -v '^!' > mosdns_adrules_processed.txt

      - name: Process domains_raw.txt (ignore lines starting with "!")
        run: |
          grep -v '^!' domains_raw.txt > domains_processed.txt

      - name: Process dns.txt (remove starting "||", ending "^", and ignore lines starting with "!")
        run: |
          # 对每一行删除开头的 "||" 及末尾的 "^"
          sed -E 's/^\|\|//; s/\^$//' dns_raw.txt | grep -v '^!' > dns_processed.txt

      - name: Process adblockdomain.txt (ignore lines starting with "!")
        run: |
          grep -v '^!' adblockdomain_raw.txt > adblockdomain_processed.txt

      - name: Merge files and remove duplicate entries
        run: |
          # 合并所有处理后的文件，删除空行，然后排序去重生成最终文件 domains.txt
          cat mosdns_adrules_processed.txt domains_processed.txt dns_processed.txt adblockdomain_processed.txt | sed '/^\s*$/d' | sort -u > domains.txt
          echo "Merged domains.txt generated with $(wc -l < domains.txt) unique lines."

      - name: Commit merged file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add domains.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update merged domains file"
            git push
          else
            echo "No changes to commit."
          fi
